from typing import Optional

from pydantic import BaseModel, Field


class SubscriptionOut(BaseModel):
    """A namespace's full subscription state, after `POST /subscriptions`
    has applied one of its two updates (base or extra)."""

    namespace_id: str = Field(..., description="Namespace (tenant) id.")
    plan_id: str = Field(..., description="Id of the plan just subscribed.")
    plan_name: str = Field(..., description="Name of the plan just subscribed.")
    is_extra: bool = Field(
        ...,
        description=(
            "Whether this subscription was an extra (quota) subscription "
            "(`plan.quota` was not `null`) rather than a base one."
        ),
    )
    subscription_plan_id: Optional[str] = Field(
        default=None, description="Id of the namespace's current base plan."
    )
    subscription_start_date: Optional[str] = Field(
        default=None, description="Base subscription start date (`YYYY-MM-DD`)."
    )
    subscription_end_date: Optional[str] = Field(
        default=None, description="Base subscription end date (`YYYY-MM-DD`)."
    )
    extra_subscription_plan_id: Optional[str] = Field(
        default=None, description="Id of the namespace's current extra (quota) plan."
    )
    extra_subscription_start_date: Optional[str] = Field(
        default=None, description="Extra subscription start date (`YYYY-MM-DD`)."
    )
    extra_subscription_end_date: Optional[str] = Field(
        default=None, description="Extra subscription end date (`YYYY-MM-DD`)."
    )
    oiu_generated: Optional[int] = Field(
        default=None,
        description=(
            "Remaining quota balance generated by extra subscriptions, "
            "added to or replaced depending on whether the previous extra "
            "period had already ended (see `POST /subscriptions`)."
        ),
    )
